apiVersion: v1
kind: Pod
metadata:
  name: veos-pod
  labels:
    purpose: demo-veos
spec:
  containers:
    - name: veos-container
      image: hazimxpressai/veos:beta0  # Get the veos docker image
      workingDir: /root
      volumeMounts:
        - name: veos
          mountPath: /var/opt/nec/ve/veos
        - name: dev
          mountPath: /dev
        - name: home
          mountPath: ${HOME}
      env:
        - name: HIP_VISIBLE_DEVICES
          value: "0" # # 0,1,2,...,n for running on GPU and select the GPUs, -1 for running on CPU
      command: ["/bin/bash", "-c", "--"]
      # args: ["--device=`readlink -f /dev/veslot0`:`readlink -f /dev/veslot0` -v /dev:/dev:z -v /var/opt/nec/ve/veos:/var/opt/nec/ve/veos:z -v ${HOME}:${HOME}:z -it veos:latest ${HOME}/binary"]
      #  [
      #    "--device=<path to host ve device file>:<path to ve device file in container> -v /dev:/dev:z -v /var/opt/nec/ve/veos:/var/opt/nec/ve/veos:z -v <pass to host binary directry>:<pass to container binary directry>:z -it <image ID> <pass to binary in container>",
      #  ]
      args: ["tail", "-f", "/dev/null"]
      resources:
        limits:
          nec.com/ve: 1 # requesting a GPU
  volumes:
    - name: veos
      hostPath:
        path: /var/opt/nec/ve/veos
    - name: dev
      hostPath:
        path: /dev
    - name: home
      hostPath:
          path: ${HOME}
