apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: necve-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: necve-dp-ds
  template:
    metadata:
      annotations: #annotations here is deprecated (remove this)
        scheduler.alpha.kubernetes.io/critical-pod: "" #remove this
      labels:
        name: necve-dp-ds
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - image: hazimxpressai/k8s-device-plugin:beta0
          name: necve-dp-cntr
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: dp
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys #might not be necessary
              mountPath: /sys
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys #probably unnecessary
          hostPath:
            path: /sys
