apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: necve-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: necve-dp-ds
  template:
    metadata:
      annotations: 
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: necve-dp-ds
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - image: ve/k8s-device-plugin
          name: necve-dp-cntr
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: dp
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys 
              mountPath: /sys
            - name: veinfo
              mountPath: /root/k8s
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys 
          hostPath:
            path: /sys
        - name: veinfo
          hostPath:
            path: /var/opt/nec/k8s
             