apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: necve-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: necve-dp-ds
  template:
    metadata:
      labels:
        name: necve-dp-ds
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
        - image: ve/k8s-device-plugin
          name: necve-dp-cntr
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: dp
              mountPath: /var/lib/kubelet/device-plugins
            - name: sys 
              mountPath: /sys
            - name: dev
              mountPath: /dev
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys 
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev

             