apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque #default value of secret type
data: #The key-value pair we come up with
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
